### PR TITLE
Added several keywords, such as 'check not equals' and 'delete cookies'.

### PR DESCRIPTION
**Pull request by boukeb**
Added some general purpose keywords, as already used in two other projects.
- check not equals
- check not matches
- delete cookies
- respond to dialog

### CODE REVIEW

**Comment by greyarch** [comment]
Bouke, do we really need the "check not ..." keywords? I think both not equal and not match behaviours can be achieved with "check matches". Admittedly, the regex will be a bit more gnarly, but I am not certain added these 2 keywords is justified. Do you have this use case a lot?

**Comment by boukeb** [comment]
Gantcho, 

Theoretically I agree with you, but in practice testers find it hard to
create regular expressions more complex than /.*Amsterdam.*/. For RAPP
we used it a lot and it is also used in the ISZW project. 

Regards,
Bouke 

On 2016-01-06 08:55, Greyarch BV wrote:

> Bouke, do we really need the "check not ..." keywords? I think both not equal and not match behaviours can be achieved with "check matches". Admittedly, the regex will be a bit more gnarly, but I am not certain added these 2 keywords is justified. Do you have this use case a lot? 
> 
> --
> Reply to this email directly or view it on GitHub [1].

  

Links:
------
[1] https://github.com/testxio/testx/pull/5#issuecomment-169261307

**Comment by greyarch** [comment]
Ok, will merge them.

**Comment by greyarch** [comment]
'deleteCookies' keyword looks suspicious, you execute the cookie deletion immediately and not when the keyword is invoked. I do not think this works.

**Comment by greyarch** [comment]
@boukeb, please add documentation for the new keywords to the README.

**Pull request merged**
